### ISSUE TITLE
Issues with release build

### ISSUE THREAD

**Issue by mattie47** [ar51an/raspberrypi-fan-control#6]
As per below, when I try run the binary from the 3.0 release, I get `-bash: ./fan-control: cannot execute: required file not found`

Meanwhile if I compile it myself, things work. 

```
pi@raspberrypi:/opt/gpio/fan $ sudo wget -c https://github.com/ar51an/raspberrypi-fan-control/releases/download/v3.0/fan-control-release-3.0.tar.gz -O - | sudo tar -xz

Redirecting output to ‘wget-log’.
pi@raspberrypi:/opt/gpio/fan $ ll
total 40
-rwxr-xr-x 1 root root 14616 Feb  7 21:39 fan-control.backup
-rwxr-xr-x 1 pi   pi    9938 Feb  7 21:39 fan-control.c
drwxr-xr-x 4 pi   pi    4096 Nov 15  2022 fan-control-release-3.0
-rwxr-xr-x 1 root root   192 Feb  7 20:59 params.conf
-rw-r--r-- 1 root root  2262 Feb  8 17:05 wget-log
pi@raspberrypi:/opt/gpio/fan $ cd fan-control-release-3.0/
pi@raspberrypi:/opt/gpio/fan/fan-control-release-3.0 $ cd build/
pi@raspberrypi:/opt/gpio/fan/fan-control-release-3.0/build $ ll
total 72
-rwxr-xr-x 1 root root 67816 Dec 20 06:53 fan-control
-rw-r--r-- 1 root root   161 Dec 20 06:48 params.conf
pi@raspberrypi:/opt/gpio/fan/fan-control-release-3.0/build $ sudo ./fan-control
sudo: unable to execute ./fan-control: No such file or directory
pi@raspberrypi:/opt/gpio/fan/fan-control-release-3.0/build $ ./fan-control
-bash: ./fan-control: cannot execute: required file not found
```

Meanwhile compiling:

```
pi@raspberrypi:~/repos/raspberrypi-fan-control/src $ sudo ./fan-control

pi@raspberrypi:~/repos/raspberrypi-fan-control/src $ ll
total 8
-rw-r--r-- 1 pi pi 6744 Feb  8 16:45 fan-control.c
pi@raspberrypi:~/repos/raspberrypi-fan-control/src $ sudo gcc -Wall -O2 fan-control.c -o fan-control -lpigpio -lsystemd

pi@raspberrypi:~ $ journalctl -f
Feb 08 17:13:26 raspberrypi fan-control[6354]: Config values loaded: PWM_PIN=19 | TACHO_PIN=24 | RPM_MAX=5000 | RPM_MIN=1500 | RPM_OFF=0 | TEMP_MAX=55 | TEMP_LOW=40 | WAIT=5000 | TACHO_ENABLED=0 | THERMAL_FILE=/sys/class/thermal/thermal_zone0/temp
Feb 08 17:13:26 raspberrypi fan-control[6354]: Initialized and running ...
Feb 08 17:13:26 raspberrypi fan-control[6354]: [PWM] Temp: 51 | TempDiff: 73.3% | RPM: 3666

Feb 08 17:13:31 raspberrypi fan-control[6354]: [PWM] Temp: 51 | TempDiff: 73.3% | RPM: 3666
Feb 08 17:13:36 raspberrypi fan-control[6354]: [PWM] Temp: 48 | TempDiff: 53.3% | RPM: 2666
Feb 08 17:13:41 raspberrypi fan-control[6354]: [PWM] Temp: 49 | TempDiff: 60.0% | RPM: 2999

```

RPI 4 info:
```

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

pi@raspberrypi:~ $ hostnamectl
 Static hostname: raspberrypi
       Icon name: computer
Operating System: Raspbian GNU/Linux 12 (bookworm)
          Kernel: Linux 6.1.0-rpi7-rpi-v8
    Architecture: arm64

```

Just curious if anyone else has had issues with the binary in the releases.

**Comment by ar51an** [comment]
I just downloaded the release and executed the binary, it worked fine. No one complained about the binary in the release in 3 years.

![image](https://github.com/ar51an/raspberrypi-fan-control/assets/11185794/4b90e3ba-60a7-454c-bd79-cafa64938deb)

Possible reasons for the error you are getting:
1. Binary is not executable
   (Binary is executable in the tarball and from your output it clearly shows it is executable)
2. Binary was compiled on 64Bit and you are trying to run it on 32Bit
   (The output you posted above shows you are using 64Bit OS)
3. Something different with your PATH variable or aliases

Are you able to execute any other binary on your system with relative path?

What happens if you give the absolute path of the binary?
`sudo /opt/gpio/fan/fan-control-release-3.0/build/fan-control`

**Edit:**
One more thing, did you have the pigpio installed when you were trying to run the binary?
If any dependency is missing while executing the binary it will throw file not found error.

You an verify dynamic dependencies of any binary/library with below cmd: 
`ldd fan-control`

For each line there should be no "file not found" error.

**Comment by mattie47** [comment]
Hey @ar51an 

You've hit the nail on the head. 

I'm running 32 bit Raspi OS (despite the uname output given the impression of x64bit)

```
pi@raspberrypi:/opt/gpio/fan $ getconf LONG_BIT
32
```

I just tried the binary on another pi 4 running an older version of Raspi OS and also had the same issue. 

I didn't realise the build provided was x64 bit. 

Thanks for clarifying.
